Import necessary library

In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [10]:
from sklearn.datasets import make_regression
X ,y =make_regression(n_samples=2000,random_state=1)

In [11]:
X

array([[ 1.24656308, -0.00262717,  1.16177117, ..., -0.14381404,
         1.04897789,  0.36642707],
       [ 1.98789962, -0.74289827,  0.46392306, ..., -0.07953001,
         0.88431814, -0.12744446],
       [-1.18110317, -0.4599301 ,  1.07125243, ...,  0.41026575,
         0.75133724,  0.39310924],
       ...,
       [ 0.10949255, -0.93311559,  1.06941626, ..., -0.15958241,
        -1.09792226,  0.16945106],
       [-0.59682953,  0.91196902,  0.32905821, ..., -0.49513463,
         1.30232475, -0.67180649],
       [ 0.88513231, -0.95744249,  1.24415716, ..., -0.03960346,
        -0.44315668,  1.04897287]])

In [12]:
y

array([-244.6379103 ,  338.19201455, -369.33489019, ...,   89.84615892,
         40.23247176, -113.19250449])

In [13]:
from sklearn.model_selection import train_test_split
X_train ,X_test ,y_train ,y_test =train_test_split(X,y,test_size=0.3,random_state=12)

In [14]:
X_train

array([[-0.3102569 , -0.35427619,  0.39650492, ...,  1.26959618,
        -0.30150675, -2.26888313],
       [ 1.28044403,  1.73871889,  0.84672379, ..., -0.51392111,
        -1.44702872, -1.61237671],
       [ 0.58455701, -0.18854658,  0.10667214, ...,  0.3039744 ,
        -0.61025316, -1.2003673 ],
       ...,
       [-0.87636515,  2.1606535 ,  0.69440495, ...,  0.68105216,
         0.4741391 , -1.15527546],
       [ 0.8521572 , -0.50782106, -0.47473822, ..., -2.60530035,
         1.69787155, -0.57837416],
       [-0.92166369,  1.42898437,  0.15152283, ...,  1.97076816,
        -2.0457776 , -0.01832535]])

In [15]:
X_test

array([[-2.47913336e+00, -1.32941774e+00,  7.55895123e-01, ...,
         4.32523466e-01,  6.55392088e-01, -4.89171664e-01],
       [ 1.21935522e+00,  9.17253872e-01, -6.24653153e-02, ...,
         6.51603617e-01,  3.19617561e-02,  5.35192360e-01],
       [ 1.59296974e+00,  1.29511140e-01,  3.47589377e-01, ...,
         1.87142477e-01,  3.10548285e-02,  9.68582688e-01],
       ...,
       [-1.62038450e-01,  7.36388470e-01,  1.29887994e+00, ...,
         1.34411245e+00,  9.42955805e-01,  6.33662061e-01],
       [-1.37604633e-03,  7.85995759e-01,  8.75557342e-02, ...,
         7.93833204e-01, -2.16655900e+00, -1.92740972e+00],
       [ 1.92506088e+00,  1.44194971e+00,  1.00439787e+00, ...,
         4.27048308e-01,  2.08982884e-01, -1.65906685e-01]])

In [16]:
pip install XGBoost

Note: you may need to restart the kernel to use updated packages.


In [18]:
from xgboost import XGBRegressor
classifier = XGBRegressor()
classifier.fit(X_train ,y_train)
y_pred =classifier.predict(X_test)
y_pred

array([-4.84582748e+01, -2.78153076e+02,  2.66153595e+02, -2.84341675e+02,
        2.13032181e+02,  1.37056305e+02,  3.26282578e+01,  2.20874367e+01,
       -8.64445877e+01,  3.58214325e+02, -1.93532181e+01, -6.84206467e+01,
        1.23037262e+02,  9.77429962e+01, -3.98718262e+01,  1.60419876e+02,
        1.17337967e+02, -2.32512665e+01, -1.33884979e+02, -2.05439789e+02,
        1.23851616e+02,  2.72379272e+02,  1.46730026e+02, -2.72791538e+01,
       -1.70996857e+01,  2.27688080e+02,  5.51205559e+01,  4.00659676e+01,
        9.00577545e+01, -2.92101349e+02, -9.04593124e+01, -7.17330265e+00,
        2.48543530e+01,  3.79272980e+02,  1.23011026e+01, -7.40918655e+01,
        1.67516876e+02,  7.76638718e+01,  1.01113625e+02, -1.25347473e+02,
        1.75748993e+02,  1.29710358e+02, -1.35450897e+02,  1.50316589e+02,
        1.33637589e+02,  1.01831772e+02,  1.05001694e+02, -2.33605213e+01,
        5.96004448e+01,  1.00670555e+02,  3.40004486e+02, -6.01471901e+01,
       -1.25439926e+02, -

In [19]:
from sklearn.metrics import r2_score
print(r2_score(y_test ,y_pred))

0.8362608636937139


hyperparameter tunning

In [20]:
from sklearn.model_selection import GridSearchCV
param_grid ={"n_estimators":[100,150],
            "learning_rate":[0.001,0.1,1],
            "loss":["squared_error","absolute_error"]}
grad =XGBRegressor()

In [21]:
clf =GridSearchCV(estimator=grad ,param_grid=param_grid ,cv =5,verbose=3)

In [22]:
clf.fit(X_train ,y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits
[CV 1/5] END learning_rate=0.001, loss=squared_error, n_estimators=100;, score=0.102 total time=   7.0s
[CV 2/5] END learning_rate=0.001, loss=squared_error, n_estimators=100;, score=0.100 total time=   3.7s
[CV 3/5] END learning_rate=0.001, loss=squared_error, n_estimators=100;, score=0.094 total time=   5.2s
[CV 4/5] END learning_rate=0.001, loss=squared_error, n_estimators=100;, score=0.093 total time=   6.2s
[CV 5/5] END learning_rate=0.001, loss=squared_error, n_estimators=100;, score=0.103 total time=   4.7s
[CV 1/5] END learning_rate=0.001, loss=squared_error, n_estimators=150;, score=0.147 total time=   9.1s
[CV 2/5] END learning_rate=0.001, loss=squared_error, n_estimators=150;, score=0.144 total time=  11.5s
[CV 3/5] END learning_rate=0.001, loss=squared_error, n_estimators=150;, score=0.137 total time=   6.5s
[CV 4/5] END learning_rate=0.001, loss=squared_error, n_estimators=150;, score=0.134 total time=   8.6s
[CV

GridSearchCV(cv=5,
             estimator=XGBRegressor(base_score=None, booster=None,
                                    callbacks=None, colsample_bylevel=None,
                                    colsample_bynode=None,
                                    colsample_bytree=None, device=None,
                                    early_stopping_rounds=None,
                                    enable_categorical=False, eval_metric=None,
                                    feature_types=None, gamma=None,
                                    grow_policy=None, importance_type=None,
                                    interaction_constraints=None,
                                    learning_rate=None, m...
                                    max_cat_to_onehot=None, max_delta_step=None,
                                    max_depth=None, max_leaves=None,
                                    min_child_weight=None, missing=nan,
                                    monotone_constraints=None,
                                    multi_strategy=None, n_estimators=None,
                                    n_jobs=None, num_parallel_tree=None,
                                    random_state=None, ...),
             param_grid={'learning_rate': [0.001, 0.1, 1],
                         'loss': ['squared_error', 'absolute_error'],
                         'n_estimators': [100, 150]},
             verbose=3)

In [23]:
clf.best_estimator_

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             gamma=None, grow_policy=None, importance_type=None,
             interaction_constraints=None, learning_rate=0.1,
             loss='squared_error', max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=150,
             n_jobs=None, num_parallel_tree=None, ...)

In [24]:
clf.best_score_

0.846322530347963