Import necessary library

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [2]:
from sklearn.datasets import make_classification
X ,y =make_classification(n_samples=2000,n_classes=2,random_state=1)

In [3]:
X

array([[-0.62070677,  1.39769519,  0.1034997 , ..., -0.34409714,
         0.62197727,  1.95988272],
       [ 0.90592186,  1.9199751 , -0.7783715 , ..., -1.30560469,
        -1.54476766, -0.24532071],
       [ 0.27902104,  0.85887666,  1.20780417, ...,  2.50374447,
        -0.16497195,  0.4694019 ],
       ...,
       [ 0.40426899, -0.61988039,  0.87588292, ...,  0.61529851,
         0.97573222, -0.44106879],
       [-0.02512151, -1.05618212, -0.2345739 , ..., -1.6839064 ,
        -0.33327389, -0.67962089],
       [-1.46739126, -0.12314487,  0.66858242, ...,  1.92945851,
        -0.97878106,  1.68813888]])

In [4]:
y

array([1, 0, 1, ..., 0, 0, 1])

In [5]:
from sklearn.model_selection import train_test_split
X_train ,X_test ,y_train ,y_test =train_test_split(X,y,test_size=0.3,random_state=12)

In [6]:
X_train

array([[ 0.18591003,  1.01964602, -0.43524364, ..., -0.03576256,
        -0.2717688 , -1.48430318],
       [ 1.39279567, -0.76634569,  0.64186693, ...,  0.15215346,
         0.81821817,  0.9212206 ],
       [-0.68806067, -0.74391338, -0.66215398, ..., -0.83661639,
         0.1600746 , -0.27682618],
       ...,
       [ 0.35698425,  0.04365315,  0.5947503 , ..., -0.13436769,
         0.47239105, -0.66004783],
       [ 0.30349003, -0.11437617,  0.58119483, ...,  1.00430411,
         1.40999468,  1.12285401],
       [-2.0001416 , -0.07342333, -0.00754763, ..., -0.54784178,
         0.37875495, -1.12537847]])

In [7]:
X_test

array([[ 1.48302491,  0.81204809,  2.21283069, ...,  0.46825488,
        -0.17453995, -0.60441915],
       [-0.38254529,  0.90192383, -2.28183109, ..., -1.55464802,
         1.55654238, -1.00445501],
       [-0.38597037,  1.43468766,  1.87689632, ...,  0.27974488,
        -0.29362533, -0.60974881],
       ...,
       [ 1.01342739, -0.41748454, -0.43298372, ...,  0.50132775,
         0.37080188, -0.94416961],
       [ 0.87955393,  1.50491049, -1.43602736, ...,  1.10994221,
         0.59013099,  1.19538247],
       [-0.75219267,  0.89789487,  2.62176802, ..., -2.53760404,
        -1.31086656, -0.12305445]])

In [8]:
!pip install XGboost

In [9]:
from xgboost import XGBClassifier
classifier =XGBClassifier()
classifier.fit(X_train ,y_train)
y_pred =classifier.predict(X_test)
y_pred

array([0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1,

In [10]:
from sklearn.metrics import accuracy_score,classification_report ,confusion_matrix
print(confusion_matrix(y_test ,y_pred))

[[280  20]
 [ 23 277]]


In [11]:
print(accuracy_score(y_test ,y_pred))

0.9283333333333333


In [12]:
print(classification_report(y_test ,y_pred))

              precision    recall  f1-score   support

           0       0.92      0.93      0.93       300
           1       0.93      0.92      0.93       300

    accuracy                           0.93       600
   macro avg       0.93      0.93      0.93       600
weighted avg       0.93      0.93      0.93       600



hyperparameter tunning

In [13]:
from sklearn.model_selection import GridSearchCV
param_grid ={"loss":["log_loss","exponential"],
            "learning_rate":[0.001,0.005],
            "n_estimators":[1,2,3,4,5]}
Grad =XGBClassifier()

In [14]:
clf =GridSearchCV(estimator=Grad ,param_grid=param_grid ,cv =5,verbose=3)

In [15]:
clf.fit(X_train ,y_train)

Fitting 5 folds for each of 20 candidates, totalling 100 fits
[CV 1/5] END learning_rate=0.001, loss=log_loss, n_estimators=1;, score=0.500 total time=   0.0s
[CV 2/5] END learning_rate=0.001, loss=log_loss, n_estimators=1;, score=0.504 total time=   0.1s
[CV 3/5] END learning_rate=0.001, loss=log_loss, n_estimators=1;, score=0.504 total time=   0.1s
[CV 4/5] END learning_rate=0.001, loss=log_loss, n_estimators=1;, score=0.504 total time=   0.1s
[CV 5/5] END learning_rate=0.001, loss=log_loss, n_estimators=1;, score=0.504 total time=   0.1s
[CV 1/5] END learning_rate=0.001, loss=log_loss, n_estimators=2;, score=0.500 total time=   0.2s
[CV 2/5] END learning_rate=0.001, loss=log_loss, n_estimators=2;, score=0.504 total time=   0.2s
[CV 3/5] END learning_rate=0.001, loss=log_loss, n_estimators=2;, score=0.504 total time=   0.1s
[CV 4/5] END learning_rate=0.001, loss=log_loss, n_estimators=2;, score=0.504 total time=   0.0s
[CV 5/5] END learning_rate=0.001, loss=log_loss, n_estimators=2;,

GridSearchCV(cv=5,
             estimator=XGBClassifier(base_score=None, booster=None,
                                     callbacks=None, colsample_bylevel=None,
                                     colsample_bynode=None,
                                     colsample_bytree=None, device=None,
                                     early_stopping_rounds=None,
                                     enable_categorical=False, eval_metric=None,
                                     feature_types=None, gamma=None,
                                     grow_policy=None, importance_type=None,
                                     interaction_constraints=None,
                                     learning_rate=None,...
                                     max_cat_threshold=None,
                                     max_cat_to_onehot=None,
                                     max_delta_step=None, max_depth=None,
                                     max_leaves=None, min_child_weight=None,
                                     missing=nan, monotone_constraints=None,
                                     multi_strategy=None, n_estimators=None,
                                     n_jobs=None, num_parallel_tree=None,
                                     random_state=None, ...),
             param_grid={'learning_rate': [0.001, 0.005],
                         'loss': ['log_loss', 'exponential'],
                         'n_estimators': [1, 2, 3, 4, 5]},
             verbose=3)

In [18]:
clf.best_estimator_

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.005,
              loss='log_loss', max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=5,
              n_jobs=None, num_parallel_tree=None, ...)

In [19]:
clf.best_score_

0.9335714285714285